world:
- type: robot-lab
  pose: { x: 0, y: 0, z: 0 }

plugins:
  - name: gui_server
    type: ed_gui_server/gui_server

  - name: tf_publisher
    type: ed/tf_publisher
    parameters:
      root_frame_id: /map
      exclude: optional_ids_to_exclude
